package com.mertkar.besinkod;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DatabaseHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "ekod.db";
    private static final int DATABASE_VERSION = 1;

    public static final String TABLE_NAME = "ekodlar";
    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_EKOD = "ekod";
    public static final String COLUMN_KIMYASAL_ADI = "kimyasaladi";
    public static final String COLUMN_ACIKLAMA = "aciklama";
    public static final String COLUMN_HELAL_HARAM = "helalharam";

    private static final String TABLE_CREATE =
            "CREATE TABLE " + TABLE_NAME + " (" +
                    COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    COLUMN_EKOD + " TEXT, " +
                    COLUMN_KIMYASAL_ADI + " TEXT, " +
                    COLUMN_ACIKLAMA + " TEXT, " +
                    COLUMN_HELAL_HARAM + " TEXT);";

    public DatabaseHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(TABLE_CREATE);
        // Örnek veriler ekleyin
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E100', 'Kurkumin', 'Doğal renk pancardan ve Yellowrootun gövdesinden (Curcuma longa ve Curcuma domestic) izole edilir. Turmerik ham ekstrakt iken kurkumin saf bileşiktir. Köri tozundaki sarı rengi verir.Gıda renklendiricisi, pH ya (asitlik) bağlı olarak renk sınıfı sarıdan kırmızıya. Suda çok çözünmez. Kurkumin için vücut ağırlığı üzerinden 1 mg/kg, ve turmerik için 0.3 mg/kg dır. Gıdalarda kullanılan konsantrasyonlarda bilinen yan etkisi yoktur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E101', 'riboflavin (B2 vitamini)', 'Doğal renk süt, yumurta, karaciğer ve sebzeler gibi birçok gıda da mevcuttur. Ticari olarak mayalardan hazırlanır böylece sentetik olarak üretilir. Sarı gıda renklendiricisi. Suda çok çözünmez. Kabul edilebilir günlük alım miktarı, vücut ağırlığı üzerinden 0.5 mg/kg dır. Gıdalarda kullanılan konsantrasyonlarda bilinen yan etkisi yoktur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E101a', 'riboflavin-5 fosfat', 'Riboflavin-5 - Fosfat, Riboflavinin fosfatlanmış bir türevidir ve aynı zamanda bir B2 vitamini formudur. Genellikle takviye ürünlerde ve bebek mamalarında kullanılır. Riboflavin-5 -Fosfat, vücut tarafından hızlı bir şekilde emilir ve metabolize edilir, bu da onu bazı durumlarda tercih edilen bir form haline getirir. Genellikle güvenli olarak kabul edilir ve Riboflavin ile aynı biyolojik işlevleri destekler.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E102', 'tartrazin', 'Sentetik sarı bir renklendirici madde olan Tartrazin, gıda ürünlerinde sarı ve turuncu renklerin elde edilmesinde kullanılır. Genellikle şekerleme, içecekler, hazır çorbalar ve dondurmalar gibi ürünlerde bulunur. Tartrazinin astım ve ürtiker gibi alerjik reaksiyonlara neden olabileceği bildirilmiştir. Ayrıca, bazı kişilerde hiperaktiviteyi tetikleyebilir. Güvenli kabul edilen günlük alım miktarı 7.5 mg/kg dır. Tartrazin, bazı Müslüman ülkelerde şüpheli olarak kabul edilebilir, bu nedenle dikkatle kullanılmalıdır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E103', 'alkannin', 'Alkanet, doğal bir kırmızı renklendirici madde olarak bilinir ve bitkilerden elde edilir. Bu madde özellikle kozmetik ürünlerde ve bazı gıda ürünlerinde kullanılabilir. Ancak, gıda ürünlerinde kullanımına birçok ülkede izin verilmemektedir, çünkü bazı sağlık riskleri taşıdığı düşünülmektedir. Alkanetin yan etkileri hakkında yeterli veri olmamakla birlikte, tüketiminden kaçınılması önerilmektedir.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E104', 'kinolin sarısı', 'Kinolin Sarısı, sentetik bir sarı renklendirici olup genellikle şekerlemelerde, içeceklerde ve bazı ilaçlarda kullanılır. Tartrazin gibi alerjik reaksiyonlara ve hiperaktiviteye neden olabileceği bildirilmiştir. Avrupa Birliği ve diğer bazı ülkelerde gıda katkı maddesi olarak kullanımına izin verilmiştir, ancak belirli bir günlük alım miktarını aşmamak şartıyla. Müslüman ülkelerde şüpheli olarak değerlendirilir ve bu nedenle dikkatli kullanılması gerekir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E105', 'katon gri', 'Yellow 2G, sentetik bir sarı renklendirici olup, özellikle şekerleme ve içeceklerde kullanılır. Ancak, bu katkı maddesi bazı ülkelerde yasaklanmıştır, çünkü hayvan deneylerinde kanserojen etkiler göstermiştir. Avrupa Birliğinde de kullanımı yasaktır. Gıdalarda nadir bulunur ve kullanımı kesinlikle önerilmez.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E106', 'riboflavin-5 - fosfat', 'B2 vitamininin bir türevidir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E110', 'sunset yellow', 'Sentetik azo boyasıdır. Sarı gıda renklendiricisidir. Suda çok çözünür.\n" +
                "Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E120', 'karmin', ' Doğal kırmızı gıda renklendiricisi, etli bitkilerin farklı türlerinde yaşayan Dactylopius coccus böceklerden ekstrakte edilir. E120 (i) saf renklendiriciyken E120 (ii) ham ekstraktır. K ırmızı gıda renklendiricisi. Suda çok çözünür. Gıdalarda kullanılan konsantrasyonlarında yan etkisi yokter. Bazı durumlarda hiperaktiviteyi arttırdığı rapor edilmiştir. En çok bilinen alerji kozmatikler kullanıldığında olan alerjidir.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E122', 'azorubin', 'Sentetik azo boyasıdır. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E123', 'amarant', 'Sentetik azo boyasıdır. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir. Sıçanlarda tümör ve yabani kadife çiçeği arasında bağlantı olduğu tespit edilmiştir , fakat insanlarda denenmemiştir. Bununla birlikte, kullanımı bazı testlerle sınırlandırılmıştır ve ADIli 0.5 mg/kg indirilmiştir.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E124', 'ponceau 4R', 'Sentetik azo boyasıdır. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E127', 'eritrosin', 'Sentetik iyodin içeren kırmızı boya. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Gıdalarda kullanılan konsantrasyonlarında bazı yan etkileri vardır. Birkaç olayda hiperaktiviteyi yükselttiği rapor edilmiştir, mutajenlerle bağlantılı olma olasılığı vardır. Eritrosin güneş ışığına duyarlılığı ile insanlarda ışığa duyarlılığın yükselmesine neden olur. Eritrosinin yüksek konsantrasyonları iyot metabolizmasıyla zarar verir. Bununla beraber, bu konsantrasyonlara gıdanın direkt komposizyonlarında ulaşılamaz.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E128', 'kırmızı 2G', 'Sentetik azo boyasıdır. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlara karşı intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir. Bununla birlikte, Kırmızı 2G anemiyi beraberinde getirebilir ve mutajenik olabilir. Sonuç olarak, kullanımı çok sınırlıdır ve ADIli düşüktür.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E129', 'allura red', 'Sentetik azo boyasıdır. Kırmızı gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir. Karışımlardaki bileşiklerin bazıları mutajenik olabilir; bu nedenle kullanımı birkaç ürünle sınırlıdır. Parçalanma ürünlerinden biri yüksek konsantrasyonlarda bulunduğu zaman hayvanlarda mesane kanserine sebep olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E131', 'patent blue V', 'Sentetik mavi renk. Mavi gıda renklendiricisidir. Suda çok çözünür. Gıdalarda kullanılan konsantrasyonlarında nadiren yan etkileri görülür. Seyrek olarak alerjik reaksiyonlar tanımlanmıştır, bunlar renklendiricinin (vücut) proteinlere bağlanması yüzündendir. Histaminin serbest bırakılmasından sorumludur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E132', 'indigo carmine', 'Mavi renk vermek için kullanılan sentetik bir boyadır ve gıda ürünlerinde, içeceklerde, dondurmalarda ve bazı kozmetik ürünlerde bulunabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E133', 'brilliant blue FCF', 'Sentetik mavi boya. Mavi gıda renklendiricisi. Suda çok çözünür. Kullanılan konsantrasyonlarda nadiren yan etki meydana gelir. Bazı alerjik reaksiyonlar rapor edilmiştir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E140', 'klorofil', 'Bütün bitkilerde ve alglerde mevcut olan doğal yeşil renktir. Ticari olarak ısırgan, çim ve yoncadan ekstrakte edilir. Yeşil, suda çözünen gıda renklendiricisi. Bilinen yan etkisi yoktur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E141', 'klorofilinler', 'Klorofilin sentetik bakır kompleksi (E140), bütün bitkilerde ve alglerde bulunan doğal yeşil renklendiricidir. E141 ticari olarak ısırgandan, çimenden ve yoncadan ekstrakte edilir. Klorofilin deesterifikasyonundan dolayı phaeophytine formundadır. Yeşil gıda renklendiricisi. E141 (i) suda çözünürken E141 (ii) yağda çözünür. Bilinen yan etkisi yoktur. E141 ısıltıldığı zaman bakır serbest kalır; bununla beraber, bakırın bu bileşik içindeki bakır konsantrasyonu toksik seviyelere ulaşmaz.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E142', 'yeşil S', 'Sentetik yeşil renk. Yeşil gıda renklendiricisidir. E142 suda çözünür, fakat asit ve alkali çözeltilerde karalı değildir. Bilinen birkaç yan etkisi vardır. Bazı durumlarda alerji ve anemi rapor edilmiştir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E150', 'karamel', 'Kahverengi karışımı, alkali, amonyak, sülfat veya bunların kombinasyonları varlığında şekerin kuru ısıtılması ve yakılması ile oluşur. Kahverenginden siyaha renklendiriciler. Suda çözünür ve spesifiktir, bazen acı tadı vardır. E150c ve E150d nın kullanılmasıyla yan etkileri belirlenmiştir, fazla miktarlarda yenilmesinden sonra bağırsaklarda problemler meydana gelebilir. Karışımlarının kompleks çeşitleri yüzünden toksikoloji testlerinde hala incelenmektedir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E150a', 'karamel', 'Kahverengi karışımı, alkali, amonyak, sülfat veya bunların kombinasyonları varlığında şekerin kuru ısıtılması ve yakılması ile oluşur. Kahverenginden siyaha renklendiriciler. Suda çözünür ve spesifiktir, bazen acı tadı vardır. E150c ve E150d nın kullanılmasıyla yan etkileri belirlenmiştir, fazla miktarlarda yenilmesinden sonra bağırsaklarda problemler meydana gelebilir. Karışımlarının kompleks çeşitleri yüzünden toksikoloji testlerinde hala incelenmektedir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E150b', 'kaustik sülfit karamel', 'Karamel II olarak bilinen bir renklendiricidir. Bu karamel türü, amonyak ve şekerin reaksiyonu ile üretilir ve genellikle gıda ve içeceklerde kullanılır. Karamel II, özellikle içeceklerde, şekerlemelerde ve bazı soslarda renk vermek için tercih edilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E150c', 'amonyak karamel', 'E150c, Karamel III olarak bilinen bir renklendiricidir. Bu karamel türü, şekerin amonyak ve sülfat ile işlenmesiyle üretilir ve genellikle gıda ve içeceklerde renk vermek için kullanılır. E150c, özellikle gazlı içeceklerde, soslarda ve bazı şekerlemelerde bulunabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E150d', 'sülfit amonyak karamel', 'E150d, Karamel IV olarak bilinen bir renklendiricidir. Bu karamel türü, şekerin amonyak ve sülfat ile işlenmesiyle üretilir ve genellikle gıda ve içeceklerde kullanılır. E150d, özellikle alkollü içeceklerde, bazı soslarda ve şekerlemelerde bulunabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E151', 'brilliant black BN', 'Sentetik azo boyasıdır. Siyah gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır, ve astım semptomlarını yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir. Bağırsaklarda, bakteriler tarafından zararlı bileşenlere dönüştürülebilir, bu nedenle ADIli çok düşük ve kullanımı sınırlıdır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E153', 'bitkisel karbon', 'Doğal element, sebzelerin yanması ile üretilir. Siyah, suda çözünmeyen renklendiricidir. Bu yüzden filtrasyon ajanı olarak kullanılır. Kullanılan konsantrasyonlarda bilinen yan etkisi yoktur. Anti-diarrhoeal ajanı olarak tıpta kullanılır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E154', 'brown FK', 'Sentetik azo boyasının karışımıdır. Kahverengi gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır, ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir. Karışımlardaki bileşiklerin bazıları mutajenik olabilir; bu nedenle kullanımı birkaç ürünle sınırlıdır.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E155', 'brown HT', 'Sentetik azo boyasıdır. Kahverengi gıda renklendiricisidir. Suda çok çözünür. Azo boyası olduğundan beri, insanlarda salisilatlar intolerans oluşturmaktadır. Buna ek olarak, histamini serbest bırakır ve astım belirtilerini yoğunlaştırır. Benzoatlarla kombinasyonlar halinde, çoçuklarda hiperaktiviteye dahi yol açabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160a', 'karotenler', 'Doğal renk çeşitli bitkilerden izole edilir; bununla birlikte, ticari olarak havuçtan elde edilir. Karotenler, kimyasal olarak benzer seriler içeren isomerlerden oluşur. Gerçek yapısı bitki türleri arasında farklılık gösterir. Suda çözünen, ekstraksiyonda kullanılan çözücüye bağlı olarak sarıdan turuncuya kadar renkleri bulunan gıda renklendiricisidir. Gıdalarda kullanılan konsantrasyonlarda bilinen yan etkisi yoktur.Yüksek konsantrasyonları deride sararmayla sonuçlanır. Karoten A vitamini kaynağı olduğundan (2 kısım karoten 1 kısım vitamin A ya eşittir), yüksek konsantrasyonları vitamin A toksititesi belirtilerine yol açar.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160b', 'anatto', 'E160b, Annatto veya Bixin olarak bilinen bir renklendiricidir. Bu doğal renk maddesi, annatto tohumlarından elde edilir ve gıdalarda sarıdan turuncuya kadar renk vermek için kullanılır. Genellikle peynir, margarin, dondurma ve bazı şekerlemelerde bulunabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160c', 'paprika ekstraktı', 'Doğal renk dolmalık biberden (Capsicum annuum) izole edilmiştir. Bu karışım temelde kapsantin ve kapsorubin içerir. Koyu kırmızı gıda renklendiricisi olduğu gibi lezzet verici ajandır. Yan etkisi bilinmemektedir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160d', 'likopen', 'Birçok sarı ve kırmızı bitkide bulunan doğal renklendiricidir. Ticari olarak domatesden izole edilir. Koyu kırmızı gıda renklendiricisidir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160e', 'beta-apo-8  karotenal', 'Birçok bitkide bulunan doğal renklendiricidir. Ticari olarak karotenden yapılır veya bitkilerden izole edilir. Yalnız yağda çözülebilen, koyu kırmısı gıda boyasıdır. Gıdalarda kullanılan konsantrasyonlarda bilinen yan etkisi yoktur. Yüksek konsantrasyonları deri renginin sararmasıyla sonuçlanabilir. A vitamini kaynağı olarak E160e, yüksek konsantrasyonlarında vitamin A toksikasyonu belirtilerine neden olabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E160f', 'eterifik beta-apo-8-karotenoik asit', 'Birçok bitkide bulunan doğal renklendiricidir. Ticari olarak E160e den yapılır veya bitkilerden izole edilir. Suda bir miktar çözülen, koyu kırmızı gıda boyasıdır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161a', 'flavoksantin', 'Birçok bitkide bulunan doğal renklendiricidir. Ticari olarak düğün çiçeğinden (Ranunculus sp.) hazırlanır. Sarı gıda boyası. Suda bir miktar çözülür.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161b', 'lutein', 'E161b, Lutein olarak bilinen bir doğal renklendiricidir. Lutein, özellikle yeşil yapraklı sebzeler ve bazı meyvelerde bulunan bir karotenoiddir ve sarı renkte olup, gıda ürünlerinde renk vermek için kullanılır. Genellikle margarin, içecekler ve bazı tatlılarda bulunabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161c', 'kapsantin', 'E161c, Capsanthin olarak bilinen bir renklendiricidir. Capsanthin, kırmızı biberlerden elde edilen doğal bir karotenoiddir ve gıdalara kırmızı renk vermek için kullanılır. Genellikle baharatlarda ve bazı işlenmiş gıdalarda bulunur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161d', 'kriptoksantin', '\"Lutein\" olarak bilinen bir gıda katkı maddesidir. Doğal bir pigment olup, özellikle ıspanak ve kara lahana gibi koyu yeşil yapraklı sebzelerde bulunur. E161d, genellikle gıdalarda renk verici olarak kullanılır ve margarin, peynir ve çeşitli hamur işlerinde bulunabilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161e', 'violoksantin', 'Birçok bitkide bulunan doğal renklendirici.Ticari olarak Viola türlerinden hazırlanır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161f', 'rhodoksantin', '\"Canthaxanthin\" olarak bilinen bir gıda katkı maddesidir. Canthaxanthin, bir karotenoid pigmentidir ve gıdalara kırmızı-turuncu renk vermek için kullanılır. Genellikle meyve ve sebzelerde bulunur, ancak gıda endüstrisinde renklendirici olarak kullanılır.Canthaxanthin, bazı hayvan yemlerinde de bulunur, bu sayede et ve yumurtaların rengini artırabilir. Ayrıca, bazı kozmetik ürünlerde ve gıda takviyelerinde de kullanılabilir. Ancak, yüksek miktarlarda tüketilmesi sağlık riskleri taşıyabilir, bu yüzden kullanımında dikkatli olunmalıdır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E161g', 'kanthoksantin', '\"Paprika Extract\" olarak bilinen bir gıda katkı maddesidir. Paprika özütü, kırmızı biberlerden elde edilir ve gıdalara kırmızı renklendirici özellik kazandırır. Özellikle çeşitli gıda ürünlerinde renk ve tat vermek için kullanılır. Paprika özütü, ayrıca bazı sağlık faydaları da sunabilir; zengin antioksidan içerikleri sayesinde vücudu serbest radikallere karşı koruyabilir. Genellikle doğal ve güvenli bir renk maddesi olarak kabul edilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E162', 'pancar kırmızısı', '\"Beetroot Red\" yani \"Pancar Kırmızısı\" olarak bilinen bir gıda katkı maddesidir. Pancar köklerinden elde edilen doğal bir renk maddesidir ve gıdalara kırmızı veya pembe renk vermek için kullanılır. E162, genellikle meyve suları, tatlılar, dondurmalar ve şekerlemelerde bulunur. Ayrıca doğal ve bitkisel bir kaynak olduğu için çoğu insan tarafından güvenli olarak kabul edilir. Pancar köklerinden elde edildiği için, aynı zamanda bazı besin değerlerini de içerebilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E163', 'antosiyaninler', 'Antosiyaninler ve antosyanidinler doğal renklendiricilerin geniş bir grubudur. Bu renklendirici meyvelerde, çiçeklerde, dutlarda, antosiyaninler ve antosyanidinlerin kombinasyonlarını içerir. Antosiyaninler her zaman karbonhidrat molekülü içerir, bunun yanında antosyanidinler de bu moleküllerden çok az bulunur. Bireysel bileşenler farklı türlerden ekstrakte edilir. E163(i)-(iii) karışımdır. (E163a sianidin; kırmızı), (E163b delfinidin; mavi), (E163c malvidin; pembe), (E164d pelargonidin; turuncu), (E164e peonidin; kırmızı-kahverengi), (E165f petunidin; koyu kırmızı)', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E170', 'kalsiyum karbonat', 'Doğal metaldir. Yüzey kaplamak için beyaz renk; anti-katılaştırma ajanı, dolgu ajanı (eczacılıkla ilgili), konserve meyvelerde stabilizördür.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E171', 'titanyum dioksit', 'Doğal beyaz mineraldir. Yüzey kaplamak için beyaz renk; üründe katmanları ayırmak için kullanılır; diş macununda beyazlatıcı ajandır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E172', 'demir oksitler ve hidroksitler', ' (Demir Oksitleri) olarak bilinen bir gıda katkı maddesidir. Demir oksitleri, çeşitli renk tonlarında bulunabilen doğal mineral pigmentlerdir ve gıdalara renk vermek için kullanılır. Özellikle kırmızı, kahverengi ve siyah renk tonları için kullanılır. E172, genellikle şekerlemeler, çikolatalar, dondurmalar, pastalar ve diğer işlenmiş gıdalarda bulunabilir. Demir oksitleri doğal ve stabil renkler sağlar ve genellikle güvenli kabul edilir. Ancak, bazı insanlar için alerjik reaksiyonlara yol açabilir, bu yüzden dikkatli kullanılması önerilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E173', 'alüminyum', 'Doğal metaldir. Gümüş gri renkli. Sadece yüzey kaplamak için kullanılır. Katkı maddesi olarak yan etkisi bilinmemektedir. Doğal gıda kaynaklarından günlük alınan alüminyum miktarı katkı maddesi olarak alındığından daha fazladır. Alüminyumun yüksek konsantrasyonları insanda çeşitli yan etkilere neden olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E174', 'gümüş', 'Doğal metaldir. Gümüş gri renklidir. Sadece yüzey kaplamak için kullanılır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E175', 'altın', 'Doğal metaldir. Altın renklidir. Sadece yüzey kaplamak için kullanılır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E180', 'litolrubin BK', 'Sentetik azo boyasıdır, alüminyum ve kalsiyum iyonları içerir. Kırmızı renklidir. Sadece peynirlerde yüzey kaplaması olarak kullanılır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E200', 'sorbik asit', 'Sorbik asit, Avrupa dağ- ağacının meyvesinde doğal olarak bulunur (Sorbus aucuparia). Ticari olarak birçok farklı kimyasal yollarla üretilir. Sorbik asit özellikle mantar ve mayalara karşı, bir koruyucudur. Bakterilere karşı etkili değildir. En iyi aktivitesi 6.5 ‘in altındaki pH değerlerindedir (asidik ve az asidik gidalar). Kulllanılan konsantrasyonlarda yan etkileri yoktur. Yalnızca insanların çok küçük bir yüzdelik oranı hafif yalancı – alerjik reaksiyonlar gösterirler. Kabul edilebilir günlük alım miktarı 25 mg/kg vücut ağırlığına kadardır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E201', 'sodyum sorbat', 'Sorbik asitin sodyum tuzu (E200), Avrupa dağ- ağacının meyvesinde (Sorbus aucuparia) doğal olarak bulunur , ardından asit isimlendirilir.Ticari olarak birçok farklı kimyasal yollarla üretilir. Sorbik asit özellikle mantar ve mayalara karşı, bir koruyucudur. Bakterilere karşı etkili değildir. En iyi aktivitesi 6.5 ‘in altındaki pH değerlerindedir (asidik ve az asidik gidalar). Sodyum sorbat sıklıkla kullanılır, çok daha iyi çözünür olduğu gibi, aktivitesi sorbik asit ile benzerdir. Kabul edilebilir günlük alım miktarı 25 mg/kg vücut ağırlığına kadardır. Kulllanılan konsantrasyonlarda yan etkileri yoktur. Yalnızca insanların çok küçük bir yüzdelik oranı hafif yalancı – alerjik reaksiyonlar gösterirler.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E202', 'potasyum sorbat', 'Sorbik asitin potasyum tuzu (E200), Avrupa dağ- ağacının meyvesinde (Sorbus aucuparia) , doğal olarak bulunur ardından asit isimlendirilir.Ticari olarak birçok farklı kimyasal yollarla üretilir. Sorbik asit özellikle mantar ve mayalara karşı, bir koruyucudur. Bakterilere karşı etkili değildir. En iyi aktivitesi 6.5 ‘in altındaki pH değerlerindedir (asidik ve az asidik gidalar). Kabul edilebilir günlük alım miktarı 25 mg/kg vücut ağırlığına kadar. Kulllanılan konsantrasyonlarda yan etkileri yoktur. Yalnızca insanların çok küçük bir yüzdelik oranı hafif yalancı – alerjik reaksiyonlar gösterirler.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E203', 'kalsiyum sorbat', 'Sorbik asitin kalsiyum tuzu (E200), Avrupa dağ- ağacının meyvesinde (Sorbus aucuparia) doğal olarak bulunur. Ticari olarak birçok farklı kimyasal yolla üretilir. Sorbik asit, özellikle mantar ve mayalara karşı bir koruyucudur. Bakterilere karşı etkili değildir. En iyi aktiviteyi 6.5 ‘in altındaki pH değerlerinde gösterir (asidik ve az asidik gıdalar). Kalsiyum sorbat başlıca süt ürünlerinde kullanılır; aktivitesi sorbik asitinkine benzerdir. Kabul edilebilir günlük alım miktarı 25 mg/kg vücut ağırlığdır. Kulllanılan konsantrasyonlarda yan etkileri yoktur. Yalnızca insanların çok küçük bir yüzdelik oranı hafif yalancı – alerjik reaksiyonlar gösterirler.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E210', 'benzoik asit', 'Benzoik asit, benzoatlar ve benzoik asit esterleri genellikle meyvelerin çoğunda, özelliklede kirazda bulunur. Kızılcık benzoik asitin oldukça zengin bir kaynağıdır. Meyvelere ek olarak, benzoatlar mantarlarada, tarçında, karanfilde ve bazı süt ürünlerinde ( bakteriyel fermentasyon sonucu ) doğal olarak bulunurlar. Ticari amaçlar için, benzoik asit toluenden kimyasal olarak hazırlanır. Benzoik asit ve benzoatlar asidik gıdalarda ,hem mayalara hem de mantara karşı koruyucu olarak kullanılır. Bakterilere karşı çok etkili değildirler ve pH 5 in üzerindeki ürünlerde ( zayıf asidik veya nötr ) etkisizdirler. Yüksek konsantrasyonları sonucunda ekşi tat ortaya çıkar, bu uygulamaları sınırlandırır. Daha iyi çözünebilmesine bağlı olarak, benzoatlar sıklıkla hazırlanır. Kabul edilebilir günlük alım miktarı 5 mg/kg vücut ağırlığı şeklindedir. Kullanılan konsantrasyonlarda yan etkileri yoktur. Bazı insanlarda benzoik asit ve benzoatlar histamini serbest bırakabilir ve böylece yalancı - alerjik reaksiyonlara neden olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E211', 'sodyum benzoat', 'Benzoik asit, benzoatlar ve benzoik asit esterleri genellikle meyvelerin çoğunda, özelliklede kirazda bulunur. Kızılcık benzoik asitin oldukça zengin bir kaynağıdır. Meyvelere ek olarak, benzoatlar mantarlarada, tarçında, karanfilde ve bazı süt ürünlerinde ( bakteriyel fermentasyon sonucu) doğal olarak bulunurlar. Ticari amaçlar için, benzoik asit toluenden kimyasal olarak hazırlanır. Benzoik asit ve benzoatlar asidik gıdalarda ,hem mayalara hem de mantara karşı koruyucu olarak kullanılır. Mantarlara karşı çok etkili değildirler ve pH 5 in üzerindeki ürünlerde ( zayıf asidik veya nötr ) etkisizdirler. Yüksek konsantrasyonları sonucunda ekşi tat ortaya çıkar, bu uygulamayı sınırlandırır. Daha iyi çözünebilmesine bağlı olarak, benzoatlar sıklıkla tercih edilirler. Kullanılan konsantrasyonlarda yan etkileri yoktur. Bazı insanlarda benzoik asit ve benzoatlar histamini serbest bırakabilir ve böylece yalancı - alerjik reaksiyonlara neden olur. Kabul edilebilir günlük alım miktarı 5 mg/kg vücut ağırlığı kadardır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E212', 'potasyum benzoat', 'Benzoik asit, benzoatlar ve benzoik asit esterleri genellikle meyvelerin çoğunda, özelliklede kirazda bulunur. Kızılcık benzoik asitin oldukça zengin bir kaynağıdır. Meyvelere ek olarak, benzoatlar mantarlarada, tarçında, karanfilde ve bazı süt ürünlerinde ( bakteriyel fermentasyon sonucu) doğal olarak bulunurlar. Ticari amaçlar için, benzoik asit toluenden kimyasal olarak hazırlanır. Benzoik asit ve benzoatlar asidik gıdalarda ,hem mayalara hem de mantara karşı koruyucu olarak kullanılır. Mantarlara karşı çok etkili değildirler ve pH 5 in üzerindeki ürünlerde ( zayıf asidik veya nötr ) etkisizdirler. Yüksek konsantrasyonları sonucunda ekşi tat ortaya çıkar, bu uygulamayı sınırlandırır. Daha iyi çözünebilmesine bağlı olarak, benzoatlar sıklıkla tercih edilirler. Kabul edilebilir günlük alım miktarı 5 mg/kg vücut ağırlığı kadardır. Kullanılan konsantrasyonlarda yan etkileri yoktur. Bazı insanlarda benzoik asit ve benzoatlar histamini serbest bırakabilir ve böylece yalancı - alerjik reaksiyonlara neden olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E213', 'kalsiyum benzoat', 'Sodyum Benzoatın potasyum tuzu olan Potassium Benzoate (Potasyum Benzoat) olarak bilinen bir gıda katkı maddesidir. Genellikle bir koruyucu olarak kullanılır ve gıdalarda mikrobiyal büyümeyi önlemeye yardımcı olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E214', 'etil p-hidroksibenzoat', 'Etil p-hidroksibenzoat olarak bilinen bir gıda katkı maddesidir. E214, p-hidroksibenzoik asidin etil esteridir ve genellikle bir koruyucu olarak kullanılır. Gıdalarda ve içeceklerde mikrobiyal büyümeyi önlemeye yardımcı olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E215', 'sodyum etil p-hidroksibenzoat', 'Sodyum p-hidroksibenzoatolarak bilinen bir gıda katkı maddesidir. Genellikle bir koruyucu olarak kullanılır ve gıdalarda mikrobiyal büyümeyi engellemeye yardımcı olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E216', 'propil p-hidroksibenzoat', 'Sodyum p-hidroksibenzoat ve Etil p-hidroksibenzoat karışımıdır ve genellikle p-hidroksibenzoatlar adıyla bilinir. Gıda endüstrisinde koruyucu olarak kullanılır ve gıdalarda mikrobiyal büyümeyi önlemeye yardımcı olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E217', 'sodyum propil p-hidroksibenzoat', 'E216 ya benzer şekilde bir koruyucudur ve genellikle gıdalarda ve kozmetik ürünlerde kullanılır. E217 de mikrobiyal büyümeyi önlemeye yardımcı olur ve benzer şekilde alerjik reaksiyonlar riski taşıyabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E218', 'metil p-hidroksibenzoat', 'Koruyucu.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E219', 'sodyum metil p-hidroksibenzoat', '\"Methyl p-hydroxybenzoate\" olarak bilinen bir gıda katkı maddesidir. Genellikle Methylparaben olarak bilinir ve gıdalarda, kozmetik ürünlerde ve ilaçlarda koruyucu olarak kullanılır', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E220', 'sülfür dioksit', 'Sülfür çok yaygın bir elementtir. Sülfür dioksit sülfürün yakılması ile üretilir.Çok eski tarih ile birleştirilen koruyucu olarak kullanılır. Roma imparatorluğunda ve eski Mısırda yaygın olarak kullanılırmış. Renksiz bir gazdır, koruyucu olarak kullanılır. Ürünlerin enzimatik ve bakteriyel bozulmalarını engeller. Sülfür dioksit ürünün sıvı fazında çözünür; bu reaksiyondan çıkan asit aktiv bir etmendir. Böylece asit ve zayıf asit gıdalarda en çok etkilidir. Nötr pHta etkisizdir. Ağartma etkisi ile bir oksitlleme etmeni gibi de davranır.Kullanımı sınırlandırılmış gıdalarda (doğal) renkleri oksitlemesine rağmen un da ağartma etmeni olarak da kullanılır. Sonuç olrak, beyaz şarabın renksizleşmesini önler ve ürünlerdeki C vitaminini dengede tutar. Isıtmak, ürünlerden gaz olarak sülfür dioksiti ayırır. Kabul edilebilir günlük alım miktarı 0.7 mg/kg vücut ağırlığı şeklindedir. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Bununla birlikte astımlı hastalarda solunum problemlerine neden olabilir. Yüksek konsantrasyonlarda (normal olarak gıdalarda kullanılanın üstünde) bazı insanlarda mide rahatsızlıklarına neden olabilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E221', 'sodyum sülfat', 'Sülfürik asitin sodyum tuzudur.Sodyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur. Bir koruyucudur,asidik koşullarda sülfürik asit oluşturur. Renksizleşmeyi ve bozulmayı önlemek için en az oksitleyici ve ağartıcı etmenler kadar iyi bir koruyucu olarak kullanılır.Renksizleşme ile nitelenen bakteriyel bozulmayı maskelediği gibi, et ürünlerinde kullanılmasına izin verilmemesine rağmen et içerisinde kararmayı önler.Ekmeğin yoğurma kapasitesini geliştirmede bir parça işlev arttırıcı olarak kullanılır. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Alkolle birleşmesiyle mahmurluk (akşamdan kalmışlık) semptomlarını arttırır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E222', 'sodyum bisülfat', 'Sülfürik asitin mono- sodyum tuzudur. Sodyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur. Asidik koşullarda, koruyucu gibi davranan sülfürik asit oluşturur. Sülfürik asitin mono- sodyum tuzu bazı ürünlerde koruyucu olarak kullanılır ve belki bir ağartıcı olarak kullanılabilir. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E223', 'sodyum metabisülfat', 'Sülfürik asitin sodyum tuzudur. Sodyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur. Asidik koşullarda, koruyucu gibi davranan sülfürik asit oluşturur. Sülfürik asitin sodyum tuzu bazı ürünlerde koruyucu olarak kullanılır ve belki bir ağartıcı olarak kullanılabilir. Kabul edilebilir günlük alım miktarı 0.7 mg/kg vücut ağırlığıdır. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E224', 'potasyum metabisülfat', 'Sülfürik asitin potasyum tuzu. Potasyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur. Asidik koşullarda, koruyucu gibi davranan sülfürik asit oluşturur. Sülfürik asitin potasyum tuzu meyvelerde ve meyve ürünlerinde koruyucu olarak kullanılır ve belki bir ağartıcı olarak kullanılabilir. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan (E221-228) da sakınmalıdırlar. Kalıntı etkisini hafifletir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E225', 'potasyum sülfat', 'Sülfürik asitin potasyum tuzudur. Potasyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz, kararsız tozdur. Asidik koşullarda, koruyucu etki yapan sülfürik asit oluşturur. Sülfürik asitin kalsiyum tuzu koruyucu olarak kullanılır ve belki şeker üretiminde bir ağartıcı olarak kullanılabilir. Sülfitkaramel (E150d) üretimi için kullanılır. Kabul edilebilir günlük alım miktarı 0.7 mg/kg vücut ağırlığıdır. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan (E221-228) da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E226', 'kalsiyum sülfat', 'Sülfürik asitin kalsiyum tuzudur. Kalsiyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur.Asidik koşullarda, koruyucu etki yapan sülfürik asit oluşturur. Sülfürik asitin kalsiyum tuzu koruyucu olarak kullanılır ve şeker üretiminde ağartıcı olarak kullanılabilir. Konserve sebzelerin katılığını (sıkılığını) artırır ( kalsiyuma bağlı olarak ). Kabul edilebilir günlük alım miktarı 0.7 mg/kg vücut ağırlığıdır. Oksitleme etkisine bağlı olarak , ürünlerdeki vitamin içeriğini azaltabilir. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan (E221-228) da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E227', 'kalsiyum bisülfat', 'Sülfürik asitin kalsiyum tuzudur. Yeşilimsi bir akışkandır, kalsiyum sülfat ile reaksiyon verir.Asidik şartlarda sülfürik asit oluştur, bir koruyucu gibi davranır. Bira üretiminde koruyucu olarak kullanılır.Konserve sebzelerin katılığını (sıkılığını) artırır ( kalsiyuma bağlı olarak ). Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan (E221-228) da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E228', 'potasyum bisülfat', 'Sülfürik asitin potasyum tuzudur. Potasyum sülfat oluşturmak için oksijen ile reaksiyona giren beyaz,kararsız tozdur.Asidik koşullarda, koruyucu etki yapan sülfürik asit oluşturur. Karaciğerde zararsız sülfata indirgenir ve idrarla vücuttan atılır. Doğal sülfata karşı toleranssız olan insanlar eklenen sülfatlardan (E221-228) da sakınmalıdırlar.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E230', 'bifenil', 'Benzenden sentezlenmiştir. Beyaz , suda çözünmeyen toz, turunçgillerin üzerinde büyüyen Penicillium mantarına karşı baskın olarak kullanılır. Konteynırları ve turunçgil meyvalarının ambalajlarını dezenfekte etmek için kullanılır. Bazen meyveler difenil çözeltisinin içerisine daldırılır, yavaşca kabuktan içeri nufuz eder ve meyvenin içerisinde kendiliğinden bulunabilir. Kabul edilebilir günlük alım miktarı 0.05 mg/kg vücut ağırlığıdır. Böbrekler tarafından değiştirilmemiş olarak vücuttan atılır.Çok sevkedilen turunçgil meyvelerine elle temas eden insanlar için hassasiyet rapor edilmiştir (gemi, kamyon).Bir başka deyişle yan etkileri yoktur.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E231', '2-hidroksibifenil', 'Fenil eterden sentezlenir. Beyaz , suda çözünmeyen toz, turunçgil meyvelerinin, elmaların,armutların üzerinde yetişen Penicillium mantarına karşı kısmen baskın olarak kullanılır. Yavaşca kabuktan içeri nüfuz eder ve meyvenin içerisinde kendiliğinden bulunabilir. Yan etkisi olmaksızın böbrekler tarafından değiştirilmemiş olarak vücuttan atılır.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E232', 'sodyum ortofenilfenol', 'Fenilfenolun sodyum tuzu , fenilether den sentezlenmiştir. Beyaz toz özellikle turunçgillerin , elmaların , ve armutların üzerinde büyüyen Penicillium mantarına karşı kullanılır. Su içerisinde oldukça çok çözünürdür ve meyvelere püskürtmekte veya meyveleri daldırmakta kullanılır. Yavaşça deriden içeri nüfuz eder ve meyvelerin içinde kendiliğinden olabilir. Normal yıkama ile kolayca temizlenir.Yenilen kalıntılar böbrekler tarafından değiştirilmeden vücuttan atılır ve ters olmayan reaksiyonları harekete geçirir.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E233', 'tiabendazol', 'Sentetik mantar öldürücüdür. Kısmen meyvelerin üzerinde, yaygın olarak kullanılan mantar öldürücüdür.Çoğunlukla meyvelerin üzerine püskürtülür; meyveler sulu bir çözeltinin içine daldırıldığında, tiabendazole sulu bir çözeltinin bileşeni de olabilir.Yalnızca meyvelerin dış yüzeylerinde kullanılabilir. Karaciğerde hidrolize edilir ve böbreklerden dışarı atılır.Belirlenen kabuledilebilir konsantrasyonlarda yan etkileri yoktur.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E234', 'nizin', 'Nisin Lactococcus lactis bakterisi tarafından üretilen bir polipeptid ( kısa protein ) antibiyotiktir, normalde peynir üretiminde kullanılır. Nisin Gram-pozitif gıda maddelerini bozan (çürüten) bakterilere karşı bir koruyucu olarak kullanılır. Kabul edilebilir günlük alım miktarı 33000 birim/kg vücut ağırlığıdır. Bir protein olduğu gibi, vücut tarafından da öyle muamele görür, ve ince bağırsakta sindirilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E235', 'natamisin', 'Nipagin veya Nipasept olarak bilinen bir gıda katkı maddesidir. Kimyasal adı Nipagin olup, genellikle Sodium 4-hydroxybenzoate veya Sodium p-hydroxybenzoate olarak bilinir. E235, bir koruyucu olarak kullanılır ve özellikle meyve ve sebzelerin yüzeyinde mikroorganizmaların büyümesini engellemeye yardımcı olur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E236', 'formik asit', 'Formik asit doğal olarak karıncalarda bulunur, fakat birçok meyvenin içerisinde ( örneğin elmalar, çilekler ve ahududular ), bal ve ısırganotlarında da bulunur. Ticari olarak sülfürik asit, sodyum hidroksit ve karbon monoksitten üretilir. Birçok mikro-organizmalara karşı koruyucu olarak kullanılır. Kokusuna bağlı olarak, kullanımı oldukça sınırlıdır. Kabul edilebilir günlük alım miktarı 3 mg/kg vücut ağırlığıdır. Karaciğerde metabolize edilir ve vücuttan atılır. Yüksek konsantrasyonlar diüretik dir. Belirlenmiş kabuledilebilir konsantrasyonlarda yan etkisi yoktur. Yüksek konsantrasyonlarda bölgesel olarak alerjik reaksiyonlar oluşabilir ( örneğin karınca ısırıkları ve ısırgan otlarıyla temas ).', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E237', 'sodyum formiat', 'Ticari olarak sodyumhidroksit ve karbonmonoksitten sentezlenir.Formik asit şeklinde doğal olarak bulunur. Mikroorganizmalara karşı koruyucu olarak kullanılır. Karaciğerde metabolize edilir ve vücuttan atılır. Yüksek konsantrasyonlar diüretik dir. Belirlenmiş kabuledilebilir konsantrasyonlarda yan etkisi yoktur. Kabul edilebilir günlük alım miktarı 3 mg/kg vücut ağırlığıdır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E238', 'kalsiyum formiat', 'Ticari olarak kalsiyum hidroksit ve karbon monoksitten sentezlenmiştir. Doğada formik asit olarak bulunur ( bak 236) . Mikroorganizmalara karşı koruyucu olarak kullanılır. Kabul edilebilir günlük alım miktarı 3 mg/kğ vücut ağırlığıdır. Karaciğer tarafından metabolize edilir ve vücuttan atılır.Yüksek konsantrasyonları diüretikdir (idrar söktürücü ) .', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E239', 'heksametilen tetramin', 'Ticari olarak formaldehid ve amonyaktan sentezlenmiştir. Mantara karşı bir koruyucu olarak kullanılır. Karaciğer tarafından metabolize edilir ve vücuttan atılır.Yüksek konsantrasyonlarının önemli yan etkileri vardır bununla birlikte gıdalarda bu konsantrasyonlara asla ulaşılamaz , tada bağlı olarak bu bildirilir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E240', 'formaldehit', 'Formaldehid normal olarak proteince zengin gıdaların ısıtılması veya tütsülenmesi ile oluşur. Ticari olarak metanolden sentezlenir. Formaldehid bakterilere karşı koruyucu olarak kullanılan bir gazdır.Formaldehid gıdaların içerisinde kullanılmaz, fakat gıda endüstrisinde conteynırları, boruları ve kapları dezenfekte etmek için kullanılır. Kozmetiklerde yaygın olrak kullanılır. Gaz gibi oldukça güçlü yan etkileri vardır ( gıdalarda yok ) Kabul edilebilir günlük alım miktarı 0.15 mg/kg vücut ağırlığıdır.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E241', 'gutarin aldehit', 'Sodyum Sülfit olarak bilinen bir gıda katkı maddesidir. Sodyum sülfit, genellikle gıdalarda bir koruyucu ve antioksidan olarak kullanılır. Gıdaların kararmasını ve bozulmasını önlemeye yardımcı olur.', 'Haram');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E242', 'dimetil dikarbonat', 'Kimyasal olarak sentezlenir. İçeceklerin içinde( soguk-sterlizasyon ) koruyucu olarak kullanılır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E243', 'beta-glukonat', 'Kalium Sorbat olarak bilinen bir gıda katkı maddesidir. Kimyasal adı Potassium Sorbate olup, genellikle bir koruyucu olarak kullanılır. E243, gıdalarda ve içeceklerde mikrobiyal büyümeyi engellemeye yardımcı olur ve ürünlerin raf ömrünü uzatır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E249', 'potasyum nitrit', 'Doğal oluşan mineral. Madenden çıkarılabilir veya kimyasal olarak sodyum nitrattan üretilebilir. Et ürünlerinde clostridium botulinuma (botulizime neden olan bir bakteri) karşı koruyucu olarak kullanılan beyaz tozdur. Kabul edilebilir günlük alım miktarı 0.06 mg/kg vücut ağırlığına kadardır. Nitritler nitroaminlerin ( muhtemelen kansorojenik ) öncüleridirler, miğdede nitritler ve proteinlerden oluşurlar.Yüksek konsantrasyonları hemoglobin ile reaksiyona girebilir. 1 yılın altındaki çocuklar için olan gıdalarda kullanılmasına izin verilmez. Küçük çocuklar farklı çeşitlerde hemoglobine sahiptirler, bu hemoglobin nitritlere karşı normal hemoglobinden çok daha fazla reaktiftir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E250', 'sodyum nitrit', 'Doğal oluşan mineral. Madenden çıkarılabilir veya kimyasal olarak sodyum nitrattan üretilebilir. Et ürünlerinde clostridium botulinuma ( botulizime neden olan bir bakteri ) karşı koruyucu olarak kullanılan beyaz tozdur . Kabul edilebilir günlük alı m miktarı 0.06 mg/kg vücut ağı rlığına kadardır. Nitritler nitroaminlerin ( muhtemelen kanserojenik ) öncüleridirler, miğ dede nitritler ve proteinlerden oluşurlar.Yüksek konsantrasyonla rı hemoglobin ile reaksiyona girebilir. 6 haftanın altındaki çocuklar için olan gıdalarda kullanılmasına izin verilmez.Küçük çocuklar farklı çeşitlerde hemoglobine sahiptirler,bu hemoglobin nitritlere karşı normal hemoglobinden çok daha fazla reaktiftir.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E251', 'sodyum nitrat', 'Doğal oluşan mineral.Neredeyse bütün sebzelerin içerisinde de bulunur. Beyaz toz, doğal renklerin solmasına karşı ve koruyucu olarak kullanılır. Nitratların yan etkileri yoktur ; bununla birlikte, ısıtılarak veya miğdenin içerisinde bulunduğunda nitratlar nitrite çevrilebilirler. Kabul edilebilir günlük alım miktarı 3.7 mg/kg vücut ağırlığıdır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E252', 'potasyum nitrat', 'Doğal oluşan mineral.Neredeyse bütün sebzelerin içerisinde de bulunur. Beyaz toz, doğal renklerin solmasına karşı ve koruyucu olarak kullanılır. Nitratların yan etkileri yoktur,fakat ısıtılarak veya miğdenin içinde nitrite (E250) dönüştürülebilir. Kabul edilebilir günlük alım miktarı 3.7 mg/kg vücut ağırlığıdır.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E260', 'asetik asit', 'Doğal bir asit, birçok meyvenin içerisinde bulunur. Bakteriyal fermentasyonla üretilir ve böylece tüm fermente ürünlerin içerisinde bulunur.Ticari olarak seker, melas, veya alkolden bakteriyal fermentasyon ile veya asetaldehitten kimyasal sentez ile üretilir. Asetik asit bakteri ve mantarlara karşı koruyucu olarak kullanılır. Mayonez içerisine Salmonellanın inaktivasyonunu arttırmak için eklenir. En yüksek aktivitesi düşük pH değerlerindedir. Asidik gıdalarda buffer olarak da kullanılır. Bir aroma bileşeni olarak da kullanılır. Yan etkileri yok, asetik asit tüm vücut hücreleri için normal bileşendir. Yalnızca (çok nadiren) sirkeyi tolere edemeyen insanlar tarafından sakınılınmalıdır. Kabul edilebilir günlük alım miktarı limitsizdir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E261', 'potasyum asetat', 'Asetik asitin potasyum tuzu, doğal bir asit, birçok meyvenin içerisinde bulunur. Bakteriyal fermentasyonla üretilir ve böylece tüm fermente ürünlerin içerisinde bulunur.Ticari olarak seker, melas, veya alkolden bakteriyal fermentasyon ile veya asetaldehitten kimyasal sentez ile üretilir. Asetatlar koruyucu ve buffer olarak kullanılırlar. Kabul edilebilir günlük alım miktarı limitsizdir. Yan etkileri yok, asetatlar tüm vücut hücreleri için normal bileşenlerdir. Yalnızca (çok nadiren) sirkeyi tolere edemeyen insanlar tarafından sakınılınmalıdır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E262', 'sodyum asetat', 'Asetik asitin sodyum tuzu, doğal bir asittir, birçok meyvede bulunur.Bakteriyal fermentasyon sonucu üretilir ve böylece tüm fermente ürünlerde bulunur.Ticari olarak seker ,melas veya alkolün bakteriler tarafından fermentasyonu ile yada acetealdehyde dan kimyasal sentez ile üretilir. Asetatlar koruyucu ve buffer olarak kullanılırlar. Yan etkisi yok, asetatlar tüm vücut hücreleri için normal bileşenlerdir. Yalnızca (çok nadir) sirke tolere edemeyen insallar tarafından sakınılmalıdır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E263', 'kalsiyum asetat', 'Asetik asitin kalsiyum tuzu, doğal bir asit, birçok meyvenin içerisinde bulunur. Bakteriyal fermentasyonla üretilir ve böylece tüm fermente ürünlerin içerisinde bulunur.Ticari olarak seker, melas, veya alkolden bakteriyal fermentasyon ile veya asetaldehitten kimyasal sentez ile üretilir. Asetatlar koruyucu ve buffer olarak kullanılırlar. Kalsiyum asetat özellikle ekmeğin içerisinde bazı spor – oluşturan organizmalara karşı kullanılır. Kabul edilebilir günlük alım miktarı limitsizdir. Yan etkileri yok, asetatlar tüm vücut hücreleri için normal bileşenlerdir. Yalnızca (çok nadiren) sirkeyi tolere edemeyen insanlar tarafından sakınılınmalıdır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E264', 'amonyum asetat', 'Sodyum Tartrat olarak bilinen bir gıda katkı maddesidir. Kimyasal adı Sodium Tartrate olup, genellikle bir asidik düzenleyici ve stabilizatör olarak kullanılır. E264, gıdalarda asidik özellikleri dengelemeye ve pH seviyesini düzenlemeye yardımcı olur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E265', 'dehidroasetik asit', ' Sodyum Tartrat olarak bilinir. Gıda katkı maddesi olarak kullanılır ve genellikle bir asidik düzenleyici ve stabilizatör olarak görev yapar. Sodyum tartrat, gıdalarda pH seviyesini düzenlemeye ve asidik özellikleri dengelemeye yardımcı olur.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E270', 'laktik asit', 'Fermente gıdaların içerisinde bakteriler tarafından üretilen doğal asittir. Tüm fermente gıdalar laktik asitçe çok zengindir.Ticari olarak nişasta ve melas üzerinde bacterial fermentasyon ile üretilirler.Yerleşik bakteriler tarafından kalın bağırsakta da büyük miktarlarda üretilir. Laktik asit ve laktatlar başlıca mayalara ve mantarlara karşı koruyucu olarak kullanılırlar. Patates ürünlerinin stabilitesini de artırmak için kullanılır, anti-oksidantları ve pektinleri arttırır ve dengeler. Kabul edilebilir günlük alım miktarı Limitsizdir. Yetişkinlerde yan etkileri yoktur. D- veya DL- laktatlar (stereoisomers) bebeklere ve küçük çocuklara verilmemelidir, henüz laktatın bu formlarını metabolise edebilecek uygun enzimler karaciğerde gelişmemiştir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E280', 'propiyonik asit', 'Birçok gıdanın içerisinde küçük miktarlarda bulunan doğal bir asit, bazen bakteriler tarafından fermente gıdaların içerisinde yüksek konsantrasyonlarda üretilir, örnegin İsviçre peynir çeşitleri.Kalın bağırsaktaki bakteriler tarafından büyük miktarlarda da üretilir.Terinde normal bir bileşenidir. Propionik asit ve propionatlar başlıca mantarlara karşı koruyucu olarak kullanılırlar.Propionik asit sıklıkla fırında pişirilen gıdalarda bakteriyal bozulmaya karşı kullanılır. Güçlü kokusuna bağlı olarak kullanımları sınırlıdır. Kabul edilebilir günlük alım miktarı limitsizdir. Yan etkileri yoktur. Propionat normal küçük bir yağ asidi zinciridir ve vücutta bir çok metabolik yolda kullanılır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E281', 'sodyum propiyonat', 'Propionik asitin sodyum tuzu, birçok gıdanın içerisinde küçük miktarlarda bulunan doğal bir asit, bazen bakteriler tarafından fermente gıdaların içerisinde yüksek konsantrasyonlarda üretilir, örnegin İsviçre peynir çeşitleri.Kalın bağırsaktaki bakteriler tarafından büyük miktarlarda da üretilir. Propionik asit ve propionatlar başlıca mantarlara karşı koruyucu olarak kullanılırlar. Yan etkileri yoktur. Propionat normal küçük bir yağ asidi zinciridir ve vücutta bir çok metabolik yolda kullanılır.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E282', 'kalsiyum propiyonat', 'Propionik asitin kalsiyum tuzu, birçok gıdanın içerisinde küçük miktarlarda bulunan doğal bir asit, bazen bakteriler tarafından fermente gıdaların içerisinde yüksek konsantrasyonlarda üretilir, örnegin İsviçre peynir çeşitleri.Kalın bağırsaktaki bakteriler tarafından büyük miktarlarda da üretilir. Propionik asit ve propionatlar başlıca mantarlara karşı koruyucu olarak kullanılırlar. Yan etkileri yoktur. Propionat normal küçük bir yağ asidi zinciridir ve vücutta bir çok metabolik yolda kullanılır. Kabul edilebilir günlük alım miktarı limitsizdir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E284', 'potasyum propiyonat', ' Doğal asit, fakat ticari olarak borondan üretilir. Borik asit ve boratlar ürünlerin asiditelerini kontrol etmek için buffer olarak kullanılırlar.Aynı zamanda bir mineral kaynagı gibi multi-vitamin/mineral ürünleri olarakta kullanılır. Gıdalardan kaynaklanan bilinen yan etkileri yok. Eczacılık hazırlamalarında konsantrasyonlar çok daha yüksektir ve birtakım yan etkilere neden olabilir. Kabul edilebilir günlük alım miktarı 0.1 mg/kg ‘a kadar kabul edilir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E283', 'potasyum propiyonat', 'Propionik asitin potasyum tuzu, birçok gıdanın içerisinde küçük miktarlarda bulunan doğal bir asit, bazen bakteriler tarafından fermente gıdaların içerisinde yüksek konsantrasyonlarda üretilir, örnegin İsviçre peynir çeşitleri. Kalın bağırsaktaki bakteriler tarafından büyük miktarlarda da üretilir. Propionik asit ve propionatlar özellikle mantarlara karşı koruyucu olarak kullanılırlar. Yan etkileri yoktur. Propionat normal küçük bir yağ asidi zinciridir ve vücutta bir çok metabolik yolda kullanılır. Kabul edilebilir günlük alım miktarı limitsizdir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E290', 'karbon dioksit', 'Normal doğal gaz. Havanın bir parçasıdır ve vücut metabolizması tarafından üretilir. Karbondioksitli ( gazlı ) içeceklerde köpürme etkisi için kullanılır. Aynı zamanda modifiye atmosfer paketlemede ve gaz konteynırlarında itici güç olarak kullanılır. Kabul edilebilir günlük alım miktarı olarak bir Limit yoktur . Gıdalardan kaynaklanan bilinen yan etkileri yoktur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E296', 'malik asit', 'Malik asit meyvelerin çoğunda ve sebzelerin birkaçında bulunan doğal bir asittir. Ticari olarak kimyasal sentez ile yapılır. Her canlı hücrenin metabolik yolunun bir parçasıdır. Asit, aroma bileşiği ve elma ve üzüm suyunda renk dengeleyici olarak kullanılır. Bilinen yan etkileri yok.Fazla miktarlardaki malik asiti metabolize etme kapasitesi olmayan küçük çocuklarda olduğu gib,yüksek konsantrasyonlarına bebek mamalarında izin verilmez. Kabul edilebilir günlük alım miktarı limitsizdir.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E297', 'fumarik asit', 'Fumarik asit doğal bir asittir sebzelerin ve meyvelerin birçoğunda bulunur.Ticari olarak şekerin mantar tarafından fermentasyonu veya kimyasal sentezle yapılır.Bu her canlı hücrenin içindeki metabolik yollun bir parçasıdır. Geniş bir aralıktaki ürünlerde yapısal stabilizatör ( dengeleyici ) ve asit olarak kullanılır. Aynı zamanda kabartma tozunda asit kaynagı olarakta kullanılır. Bilinen yan etkileri yok. Kabul edilebilir günlük alım miktarında limit yoktur.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E300', 'askorbik asit', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E301', 'sodyum askorbat', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E302', 'kalsiyum askorbat', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E303', 'potasyum askorbat', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E304', 'askorbil palmitat', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E305', 'askorbil stearat', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E306', 'doğal tokoferoller', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E307', 'sentetik alfa-tokoferol', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E308', 'gamma-tokoferol', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E309', 'delta-tokoferol', 'Antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E310', 'propil gallat', 'Antioksidan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E311', 'oktild gallat', 'Antioksidan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E312', 'dodesil gallat', 'Antioksidan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E320', 'bütillenmiş hidroksianisol (BHA)', 'Antioksidan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E321', 'bütillenmiş hidroksitoluen (BHT)', 'Antioksidan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E322', 'lesitin', 'Emülgatör ve antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E325', 'sodyum laktat', 'Emülgatör ve antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E326', 'potasyum laktat', 'Emülgatör ve antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E327', 'kalsiyum laktat', 'Emülgatör ve antioksidan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E330', 'sitrik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E331', 'sodyum sitrat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E332', 'potasyum sitrat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E333', 'kalsiyum sitrat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E334', 'tartarik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E335', 'sodyum tartarat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E336', 'potasyum tartarat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E337', 'sodyum potasyum tartarat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E338', 'fosforik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E339', 'sodyum fosfat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E340', 'potasyum fosfat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E341', 'kalsiyum fosfat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E343', 'magnezyum fosfat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E350', 'sodyum malat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E351', 'potasyum malat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E352', 'kalsiyum malat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E353', 'metatartarik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E354', 'kalsiyum tartarat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E355', 'adipik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E356', 'sodyum adipat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E357', 'potasyum adipat', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E363', 'süksinik asit', 'Asitlik düzenleyici.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E365', 'amonyum laktat', 'Asitlik düzenleyici.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E366', 'potasyum laktat', 'Asitlik düzenleyici.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E367', 'kalsiyum laktat', 'Asitlik düzenleyici.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E370', '10-undesilenik asit', 'Koruyucu.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E375', 'nikotinik asit', 'Koruyucu.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E380', 'tri (demir-III-fosfat)', 'Koruyucu.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E381', 'amonyum ferrik sitrat', 'Koruyucu.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E385', 'kalsiyum disodyum EDTA', 'Koruyucu.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E400', 'aljinik asit', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E401', 'sodyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E402', 'potasyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E403', 'amonyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E404', 'kalsiyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E405', 'propilen glikol aljinat', 'Kalınlaştırıcı ajan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E406', 'agar', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E407', 'karragenan', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E407a', 'yarı arıtılmış karragenan', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E410', 'keçiboynuzu gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E412', 'guar gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E413', 'tragakant gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E414', 'arap gamı (akasya gamı)', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E415', 'ksantan gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E420', 'sorbitol', 'Tatlandırıcı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E421', 'mannitol', 'Tatlandırıcı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E422', 'gliserol', 'Nem tutucu.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E440', 'pektin', 'Jel ajanı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E450', 'difosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E451', 'trifosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E452', 'polifosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E460', 'mikrokristalin selüloz', 'Dolgu maddesi.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E461', 'metilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E463', 'hidroksipropilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E464', 'hidroksipropil metilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E465', 'etil metil selüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E400', 'aljinik asit', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E401', 'sodyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E402', 'potasyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E403', 'amonyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E404', 'kalsiyum aljinat', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E405', 'propilen glikol aljinat', 'Kalınlaştırıcı ajan.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E406', 'agar', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E407', 'karragenan', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E407a', 'yarı arıtılmış karragenan', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E410', 'keçiboynuzu gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E412', 'guar gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E413', 'tragakant gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E414', 'arap gamı (akasya gamı)', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E415', 'ksantan gamı', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E420', 'sorbitol', 'Tatlandırıcı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E421', 'mannitol', 'Tatlandırıcı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E422', 'gliserol', 'Nem tutucu.', 'Şüpheli');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E440', 'pektin', 'Jel ajanı.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E450', 'difosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E451', 'trifosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E452', 'polifosfatlar', 'Emülgatör.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E460', 'mikrokristalin selüloz', 'Dolgu maddesi.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E461', 'metilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E463', 'hidroksipropilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E464', 'hidroksipropil metilselüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E465', 'etil metil selüloz', 'Kalınlaştırıcı ajan.', 'Helal');");
        db.execSQL("INSERT INTO " + TABLE_NAME + " (" + COLUMN_EKOD + ", " + COLUMN_KIMYASAL_ADI + ", " + COLUMN_ACIKLAMA + ", " + COLUMN_HELAL_HARAM + ") VALUES ('E466', 'karboksimetil selüloz', 'Kalınlaştırıcı ajan.', 'Helal');");

                // Diğer örnek verileri buraya ekleyin.
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME);
        onCreate(db);
    }
}